FROM openjdk:latest

LABEL author = "Viktor Talevski"

ADD ./target/api-jva-spring-boot-scientist-professional-life-module.jar ./api-jva-spring-boot-scientist-professional-life-module.jar

EXPOSE 8082

ENTRYPOINT ["java", "-jar", "./api-jva-spring-boot-scientist-professional-life-module.jar"]
